version: "3.7"

networks:
  raftel-network:

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SqlServer_Docker2024"
      ACCEPT_EULA: "Y"
    networks:
      - raftel-network