version: "3.7"

networks:
  cookbook-network:
  
services:
  cookbook-sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    ports:
      - "1433:1433"
    environment:
        SA_PASSWORD: "SqlServer_Docker2023"
        ACCEPT_EULA: "Y"
    networks:
      - cookbook-network

  raftel.demo.blazor:
    image: raftel.demo.blazor
    build:
      context: .
      dockerfile: demo/src/Raftel.Demo.Blazor/Raftel.Demo.Blazor/Dockerfile

  raftel.demo.blazor.client:
    image: raftel.demo.blazor.client
    build:
      context: .
      dockerfile: demo/src/Raftel.Demo.Blazor/Raftel.Demo.Blazor.Client/Dockerfile

  raftel.demo.blazor-1:
    image: raftel.demo.blazor-1
    build:
      context: .
      dockerfile: demo/src/Raftel.Demo.Blazor/Raftel.Demo.Blazor/Dockerfile

  raftel.demo.blazor.client-1:
    image: raftel.demo.blazor.client-1
    build:
      context: .
      dockerfile: demo/src/Raftel.Demo.Blazor/Raftel.Demo.Blazor.Client/Dockerfile

  raftel.demo.server:
    image: raftel.demo.server
    build:
      context: .
      dockerfile: demo/src/Raftel.Demo.Server/Dockerfile
