namespace Raftel.Core.AdvancedFilters;

public enum Operator
{
    Nested,
    StartsWith,
    NotStartsWith,
    EndsWith,
    NotEndsWith,
    Contains,
    NotContains,
    Equal,
    NotEqual,
    In,
    NotIn,
    Empty,
    NotEmpty,
    Null,
    NotNull,
    GreaterThan,
    LessThan,
    GreaterThanOrEqual,
    LessThanOrEqual,
    IsTrue,
    IsFalse,
    DateEqual,
    DateBefore,
    DateAfter,
    Between,
    NotBetween,
}