### YamlMime:ManagedReference
items:
- uid: Raftel.Application
  commentId: N:Raftel.Application
  id: Raftel.Application
  children:
  - Raftel.Application.DependencyInjection
  - Raftel.Application.IUnitOfWork
  langs:
  - csharp
  - vb
  name: Raftel.Application
  nameWithType: Raftel.Application
  fullName: Raftel.Application
  type: Namespace
  assemblies:
  - Raftel.Application
references:
- uid: Raftel.Application.DependencyInjection
  commentId: T:Raftel.Application.DependencyInjection
  href: Raftel.Application.DependencyInjection.html
  name: DependencyInjection
  nameWithType: DependencyInjection
  fullName: Raftel.Application.DependencyInjection
- uid: Raftel.Application.IUnitOfWork
  commentId: T:Raftel.Application.IUnitOfWork
  parent: Raftel.Application
  href: Raftel.Application.IUnitOfWork.html
  name: IUnitOfWork
  nameWithType: IUnitOfWork
  fullName: Raftel.Application.IUnitOfWork
- uid: Raftel.Application
  commentId: N:Raftel.Application
  href: Raftel.html
  name: Raftel.Application
  nameWithType: Raftel.Application
  fullName: Raftel.Application
  spec.csharp:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  spec.vb:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
