### YamlMime:ManagedReference
items:
- uid: Raftel.Application.Abstractions
  commentId: N:Raftel.Application.Abstractions
  id: Raftel.Application.Abstractions
  children:
  - Raftel.Application.Abstractions.IRequestDispatcher
  - Raftel.Application.Abstractions.IRequestHandler`2
  - Raftel.Application.Abstractions.IRequestMiddleware`2
  - Raftel.Application.Abstractions.IRequest`1
  - Raftel.Application.Abstractions.RequestDispatcher
  - Raftel.Application.Abstractions.RequestHandlerDelegate`1
  langs:
  - csharp
  - vb
  name: Raftel.Application.Abstractions
  nameWithType: Raftel.Application.Abstractions
  fullName: Raftel.Application.Abstractions
  type: Namespace
  assemblies:
  - Raftel.Application
references:
- uid: Raftel.Application.Abstractions.IRequest`1
  commentId: T:Raftel.Application.Abstractions.IRequest`1
  href: Raftel.Application.Abstractions.IRequest-1.html
  name: IRequest<TResponse>
  nameWithType: IRequest<TResponse>
  fullName: Raftel.Application.Abstractions.IRequest<TResponse>
  nameWithType.vb: IRequest(Of TResponse)
  fullName.vb: Raftel.Application.Abstractions.IRequest(Of TResponse)
  name.vb: IRequest(Of TResponse)
  spec.csharp:
  - uid: Raftel.Application.Abstractions.IRequest`1
    name: IRequest
    href: Raftel.Application.Abstractions.IRequest-1.html
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Abstractions.IRequest`1
    name: IRequest
    href: Raftel.Application.Abstractions.IRequest-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: Raftel.Application.Abstractions.IRequestDispatcher
  commentId: T:Raftel.Application.Abstractions.IRequestDispatcher
  parent: Raftel.Application.Abstractions
  href: Raftel.Application.Abstractions.IRequestDispatcher.html
  name: IRequestDispatcher
  nameWithType: IRequestDispatcher
  fullName: Raftel.Application.Abstractions.IRequestDispatcher
- uid: Raftel.Application.Abstractions.IRequestHandler`2
  commentId: T:Raftel.Application.Abstractions.IRequestHandler`2
  href: Raftel.Application.Abstractions.IRequestHandler-2.html
  name: IRequestHandler<TRequest, TResponse>
  nameWithType: IRequestHandler<TRequest, TResponse>
  fullName: Raftel.Application.Abstractions.IRequestHandler<TRequest, TResponse>
  nameWithType.vb: IRequestHandler(Of TRequest, TResponse)
  fullName.vb: Raftel.Application.Abstractions.IRequestHandler(Of TRequest, TResponse)
  name.vb: IRequestHandler(Of TRequest, TResponse)
  spec.csharp:
  - uid: Raftel.Application.Abstractions.IRequestHandler`2
    name: IRequestHandler
    href: Raftel.Application.Abstractions.IRequestHandler-2.html
  - name: <
  - name: TRequest
  - name: ','
  - name: " "
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Abstractions.IRequestHandler`2
    name: IRequestHandler
    href: Raftel.Application.Abstractions.IRequestHandler-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TRequest
  - name: ','
  - name: " "
  - name: TResponse
  - name: )
- uid: Raftel.Application.Abstractions.IRequestMiddleware`2
  commentId: T:Raftel.Application.Abstractions.IRequestMiddleware`2
  href: Raftel.Application.Abstractions.IRequestMiddleware-2.html
  name: IRequestMiddleware<TRequest, TResponse>
  nameWithType: IRequestMiddleware<TRequest, TResponse>
  fullName: Raftel.Application.Abstractions.IRequestMiddleware<TRequest, TResponse>
  nameWithType.vb: IRequestMiddleware(Of TRequest, TResponse)
  fullName.vb: Raftel.Application.Abstractions.IRequestMiddleware(Of TRequest, TResponse)
  name.vb: IRequestMiddleware(Of TRequest, TResponse)
  spec.csharp:
  - uid: Raftel.Application.Abstractions.IRequestMiddleware`2
    name: IRequestMiddleware
    href: Raftel.Application.Abstractions.IRequestMiddleware-2.html
  - name: <
  - name: TRequest
  - name: ','
  - name: " "
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Abstractions.IRequestMiddleware`2
    name: IRequestMiddleware
    href: Raftel.Application.Abstractions.IRequestMiddleware-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TRequest
  - name: ','
  - name: " "
  - name: TResponse
  - name: )
- uid: Raftel.Application.Abstractions.RequestDispatcher
  commentId: T:Raftel.Application.Abstractions.RequestDispatcher
  href: Raftel.Application.Abstractions.RequestDispatcher.html
  name: RequestDispatcher
  nameWithType: RequestDispatcher
  fullName: Raftel.Application.Abstractions.RequestDispatcher
- uid: Raftel.Application.Abstractions.RequestHandlerDelegate`1
  commentId: T:Raftel.Application.Abstractions.RequestHandlerDelegate`1
  href: Raftel.Application.Abstractions.RequestHandlerDelegate-1.html
  name: RequestHandlerDelegate<TResponse>
  nameWithType: RequestHandlerDelegate<TResponse>
  fullName: Raftel.Application.Abstractions.RequestHandlerDelegate<TResponse>
  nameWithType.vb: RequestHandlerDelegate(Of TResponse)
  fullName.vb: Raftel.Application.Abstractions.RequestHandlerDelegate(Of TResponse)
  name.vb: RequestHandlerDelegate(Of TResponse)
  spec.csharp:
  - uid: Raftel.Application.Abstractions.RequestHandlerDelegate`1
    name: RequestHandlerDelegate
    href: Raftel.Application.Abstractions.RequestHandlerDelegate-1.html
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Abstractions.RequestHandlerDelegate`1
    name: RequestHandlerDelegate
    href: Raftel.Application.Abstractions.RequestHandlerDelegate-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: Raftel.Application.Abstractions
  commentId: N:Raftel.Application.Abstractions
  href: Raftel.html
  name: Raftel.Application.Abstractions
  nameWithType: Raftel.Application.Abstractions
  fullName: Raftel.Application.Abstractions
  spec.csharp:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Abstractions
    name: Abstractions
    href: Raftel.Application.Abstractions.html
  spec.vb:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Abstractions
    name: Abstractions
    href: Raftel.Application.Abstractions.html
