### YamlMime:ManagedReference
items:
- uid: Raftel.Application.Commands.ICommand
  commentId: T:Raftel.Application.Commands.ICommand
  id: ICommand
  parent: Raftel.Application.Commands
  children: []
  langs:
  - csharp
  - vb
  name: ICommand
  nameWithType: ICommand
  fullName: Raftel.Application.Commands.ICommand
  type: Interface
  source:
    remote:
      path: src/Raftel.Application/Commands/ICommand.cs
      branch: documentation
      repo: https://github.com/franciscofsl/Raftel
    id: ICommand
    path: src/Raftel.Application/Commands/ICommand.cs
    startLine: 8
  assemblies:
  - Raftel.Application
  namespace: Raftel.Application.Commands
  summary: Represents a command that does not return a value other than a <xref href="Raftel.Domain.Abstractions.Result" data-throw-if-not-resolved="false"></xref>.
  example: []
  syntax:
    content: 'public interface ICommand : IRequest<Result>'
    content.vb: Public Interface ICommand Inherits IRequest(Of Result)
references:
- uid: Raftel.Domain.Abstractions.Result
  commentId: T:Raftel.Domain.Abstractions.Result
  parent: Raftel.Domain.Abstractions
  href: Raftel.Domain.Abstractions.Result.html
  name: Result
  nameWithType: Result
  fullName: Raftel.Domain.Abstractions.Result
- uid: Raftel.Application.Commands
  commentId: N:Raftel.Application.Commands
  href: Raftel.html
  name: Raftel.Application.Commands
  nameWithType: Raftel.Application.Commands
  fullName: Raftel.Application.Commands
  spec.csharp:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Commands
    name: Commands
    href: Raftel.Application.Commands.html
  spec.vb:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Commands
    name: Commands
    href: Raftel.Application.Commands.html
- uid: Raftel.Domain.Abstractions
  commentId: N:Raftel.Domain.Abstractions
  href: Raftel.html
  name: Raftel.Domain.Abstractions
  nameWithType: Raftel.Domain.Abstractions
  fullName: Raftel.Domain.Abstractions
  spec.csharp:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Domain
    name: Domain
    href: Raftel.Domain.html
  - name: .
  - uid: Raftel.Domain.Abstractions
    name: Abstractions
    href: Raftel.Domain.Abstractions.html
  spec.vb:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Domain
    name: Domain
    href: Raftel.Domain.html
  - name: .
  - uid: Raftel.Domain.Abstractions
    name: Abstractions
    href: Raftel.Domain.Abstractions.html
