### YamlMime:ManagedReference
items:
- uid: Raftel.Application.Commands
  commentId: N:Raftel.Application.Commands
  id: Raftel.Application.Commands
  children:
  - Raftel.Application.Commands.CommandDispatcher
  - Raftel.Application.Commands.ICommand
  - Raftel.Application.Commands.ICommandDispatcher
  - Raftel.Application.Commands.ICommandHandler`1
  langs:
  - csharp
  - vb
  name: Raftel.Application.Commands
  nameWithType: Raftel.Application.Commands
  fullName: Raftel.Application.Commands
  type: Namespace
  assemblies:
  - Raftel.Application
references:
- uid: Raftel.Application.Commands.CommandDispatcher
  commentId: T:Raftel.Application.Commands.CommandDispatcher
  href: Raftel.Application.Commands.CommandDispatcher.html
  name: CommandDispatcher
  nameWithType: CommandDispatcher
  fullName: Raftel.Application.Commands.CommandDispatcher
- uid: Raftel.Application.Commands.ICommand
  commentId: T:Raftel.Application.Commands.ICommand
  href: Raftel.Application.Commands.ICommand.html
  name: ICommand
  nameWithType: ICommand
  fullName: Raftel.Application.Commands.ICommand
- uid: Raftel.Application.Commands.ICommandDispatcher
  commentId: T:Raftel.Application.Commands.ICommandDispatcher
  parent: Raftel.Application.Commands
  href: Raftel.Application.Commands.ICommandDispatcher.html
  name: ICommandDispatcher
  nameWithType: ICommandDispatcher
  fullName: Raftel.Application.Commands.ICommandDispatcher
- uid: Raftel.Application.Commands.ICommandHandler`1
  commentId: T:Raftel.Application.Commands.ICommandHandler`1
  href: Raftel.Application.Commands.ICommandHandler-1.html
  name: ICommandHandler<TCommand>
  nameWithType: ICommandHandler<TCommand>
  fullName: Raftel.Application.Commands.ICommandHandler<TCommand>
  nameWithType.vb: ICommandHandler(Of TCommand)
  fullName.vb: Raftel.Application.Commands.ICommandHandler(Of TCommand)
  name.vb: ICommandHandler(Of TCommand)
  spec.csharp:
  - uid: Raftel.Application.Commands.ICommandHandler`1
    name: ICommandHandler
    href: Raftel.Application.Commands.ICommandHandler-1.html
  - name: <
  - name: TCommand
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Commands.ICommandHandler`1
    name: ICommandHandler
    href: Raftel.Application.Commands.ICommandHandler-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TCommand
  - name: )
- uid: Raftel.Application.Commands
  commentId: N:Raftel.Application.Commands
  href: Raftel.html
  name: Raftel.Application.Commands
  nameWithType: Raftel.Application.Commands
  fullName: Raftel.Application.Commands
  spec.csharp:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Commands
    name: Commands
    href: Raftel.Application.Commands.html
  spec.vb:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Commands
    name: Commands
    href: Raftel.Application.Commands.html
