### YamlMime:ManagedReference
items:
- uid: Raftel.Application.Abstractions.IRequestMiddleware`2
  commentId: T:Raftel.Application.Abstractions.IRequestMiddleware`2
  id: IRequestMiddleware`2
  parent: Raftel.Application.Abstractions
  children:
  - Raftel.Application.Abstractions.IRequestMiddleware`2.HandleAsync(`0,Raftel.Application.Abstractions.RequestHandlerDelegate{`1})
  langs:
  - csharp
  - vb
  name: IRequestMiddleware<TRequest, TResponse>
  nameWithType: IRequestMiddleware<TRequest, TResponse>
  fullName: Raftel.Application.Abstractions.IRequestMiddleware<TRequest, TResponse>
  type: Interface
  source:
    remote:
      path: src/Raftel.Application/Abstractions/IRequestMiddleware.cs
      branch: feature/base-types
      repo: https://github.com/franciscofsl/Raftel
    id: IRequestMiddleware
    path: src/Raftel.Application/Abstractions/IRequestMiddleware.cs
    startLine: 8
  assemblies:
  - Raftel.Application
  namespace: Raftel.Application.Abstractions
  summary: >-
    Represents a middleware component in the request pipeline that can intercept and

    modify the processing of a request before and/or after the next component is invoked.
  example: []
  syntax:
    content: 'public interface IRequestMiddleware<TRequest, TResponse> where TRequest : IRequest<TResponse>'
    typeParameters:
    - id: TRequest
      description: The type of the request.
    - id: TResponse
      description: The type of the response.
    content.vb: Public Interface IRequestMiddleware(Of TRequest As IRequest(Of TResponse), TResponse)
  nameWithType.vb: IRequestMiddleware(Of TRequest, TResponse)
  fullName.vb: Raftel.Application.Abstractions.IRequestMiddleware(Of TRequest, TResponse)
  name.vb: IRequestMiddleware(Of TRequest, TResponse)
- uid: Raftel.Application.Abstractions.IRequestMiddleware`2.HandleAsync(`0,Raftel.Application.Abstractions.RequestHandlerDelegate{`1})
  commentId: M:Raftel.Application.Abstractions.IRequestMiddleware`2.HandleAsync(`0,Raftel.Application.Abstractions.RequestHandlerDelegate{`1})
  id: HandleAsync(`0,Raftel.Application.Abstractions.RequestHandlerDelegate{`1})
  parent: Raftel.Application.Abstractions.IRequestMiddleware`2
  langs:
  - csharp
  - vb
  name: HandleAsync(TRequest, RequestHandlerDelegate<TResponse>)
  nameWithType: IRequestMiddleware<TRequest, TResponse>.HandleAsync(TRequest, RequestHandlerDelegate<TResponse>)
  fullName: Raftel.Application.Abstractions.IRequestMiddleware<TRequest, TResponse>.HandleAsync(TRequest, Raftel.Application.Abstractions.RequestHandlerDelegate<TResponse>)
  type: Method
  source:
    remote:
      path: src/Raftel.Application/Abstractions/IRequestMiddleware.cs
      branch: feature/base-types
      repo: https://github.com/franciscofsl/Raftel
    id: HandleAsync
    path: src/Raftel.Application/Abstractions/IRequestMiddleware.cs
    startLine: 17
  assemblies:
  - Raftel.Application
  namespace: Raftel.Application.Abstractions
  summary: Processes the request and optionally calls the next delegate in the pipeline.
  example: []
  syntax:
    content: Task<TResponse> HandleAsync(TRequest request, RequestHandlerDelegate<TResponse> next)
    parameters:
    - id: request
      type: '{TRequest}'
      description: The request instance.
    - id: next
      type: Raftel.Application.Abstractions.RequestHandlerDelegate{{TResponse}}
      description: The next handler in the pipeline.
    return:
      type: System.Threading.Tasks.Task{{TResponse}}
      description: A task containing the result of the request.
    content.vb: Function HandleAsync(request As TRequest, [next] As RequestHandlerDelegate(Of TResponse)) As Task(Of TResponse)
  overload: Raftel.Application.Abstractions.IRequestMiddleware`2.HandleAsync*
  nameWithType.vb: IRequestMiddleware(Of TRequest, TResponse).HandleAsync(TRequest, RequestHandlerDelegate(Of TResponse))
  fullName.vb: Raftel.Application.Abstractions.IRequestMiddleware(Of TRequest, TResponse).HandleAsync(TRequest, Raftel.Application.Abstractions.RequestHandlerDelegate(Of TResponse))
  name.vb: HandleAsync(TRequest, RequestHandlerDelegate(Of TResponse))
references:
- uid: Raftel.Application.Abstractions
  commentId: N:Raftel.Application.Abstractions
  href: Raftel.html
  name: Raftel.Application.Abstractions
  nameWithType: Raftel.Application.Abstractions
  fullName: Raftel.Application.Abstractions
  spec.csharp:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Abstractions
    name: Abstractions
    href: Raftel.Application.Abstractions.html
  spec.vb:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Abstractions
    name: Abstractions
    href: Raftel.Application.Abstractions.html
- uid: Raftel.Application.Abstractions.IRequestMiddleware`2.HandleAsync*
  commentId: Overload:Raftel.Application.Abstractions.IRequestMiddleware`2.HandleAsync
  href: Raftel.Application.Abstractions.IRequestMiddleware-2.html#Raftel_Application_Abstractions_IRequestMiddleware_2_HandleAsync__0_Raftel_Application_Abstractions_RequestHandlerDelegate__1__
  name: HandleAsync
  nameWithType: IRequestMiddleware<TRequest, TResponse>.HandleAsync
  fullName: Raftel.Application.Abstractions.IRequestMiddleware<TRequest, TResponse>.HandleAsync
  nameWithType.vb: IRequestMiddleware(Of TRequest, TResponse).HandleAsync
  fullName.vb: Raftel.Application.Abstractions.IRequestMiddleware(Of TRequest, TResponse).HandleAsync
- uid: '{TRequest}'
  commentId: '!:TRequest'
  definition: TRequest
  name: TRequest
  nameWithType: TRequest
  fullName: TRequest
- uid: Raftel.Application.Abstractions.RequestHandlerDelegate{{TResponse}}
  commentId: T:Raftel.Application.Abstractions.RequestHandlerDelegate{`1}
  parent: Raftel.Application.Abstractions
  definition: Raftel.Application.Abstractions.RequestHandlerDelegate`1
  href: Raftel.Application.Abstractions.RequestHandlerDelegate-1.html
  name: RequestHandlerDelegate<TResponse>
  nameWithType: RequestHandlerDelegate<TResponse>
  fullName: Raftel.Application.Abstractions.RequestHandlerDelegate<TResponse>
  nameWithType.vb: RequestHandlerDelegate(Of TResponse)
  fullName.vb: Raftel.Application.Abstractions.RequestHandlerDelegate(Of TResponse)
  name.vb: RequestHandlerDelegate(Of TResponse)
  spec.csharp:
  - uid: Raftel.Application.Abstractions.RequestHandlerDelegate`1
    name: RequestHandlerDelegate
    href: Raftel.Application.Abstractions.RequestHandlerDelegate-1.html
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Abstractions.RequestHandlerDelegate`1
    name: RequestHandlerDelegate
    href: Raftel.Application.Abstractions.RequestHandlerDelegate-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: System.Threading.Tasks.Task{{TResponse}}
  commentId: T:System.Threading.Tasks.Task{``1}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResponse>
  nameWithType: Task<TResponse>
  fullName: System.Threading.Tasks.Task<TResponse>
  nameWithType.vb: Task(Of TResponse)
  fullName.vb: System.Threading.Tasks.Task(Of TResponse)
  name.vb: Task(Of TResponse)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: TRequest
  name: TRequest
  nameWithType: TRequest
  fullName: TRequest
- uid: Raftel.Application.Abstractions.RequestHandlerDelegate`1
  commentId: T:Raftel.Application.Abstractions.RequestHandlerDelegate`1
  href: Raftel.Application.Abstractions.RequestHandlerDelegate-1.html
  name: RequestHandlerDelegate<TResponse>
  nameWithType: RequestHandlerDelegate<TResponse>
  fullName: Raftel.Application.Abstractions.RequestHandlerDelegate<TResponse>
  nameWithType.vb: RequestHandlerDelegate(Of TResponse)
  fullName.vb: Raftel.Application.Abstractions.RequestHandlerDelegate(Of TResponse)
  name.vb: RequestHandlerDelegate(Of TResponse)
  spec.csharp:
  - uid: Raftel.Application.Abstractions.RequestHandlerDelegate`1
    name: RequestHandlerDelegate
    href: Raftel.Application.Abstractions.RequestHandlerDelegate-1.html
  - name: <
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Abstractions.RequestHandlerDelegate`1
    name: RequestHandlerDelegate
    href: Raftel.Application.Abstractions.RequestHandlerDelegate-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TResponse
  - name: )
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
