### YamlMime:ManagedReference
items:
- uid: Raftel.Application.Queries
  commentId: N:Raftel.Application.Queries
  id: Raftel.Application.Queries
  children:
  - Raftel.Application.Queries.IQueryDispatcher
  - Raftel.Application.Queries.IQueryHandler`2
  - Raftel.Application.Queries.IQuery`1
  - Raftel.Application.Queries.QueryDispatcher
  langs:
  - csharp
  - vb
  name: Raftel.Application.Queries
  nameWithType: Raftel.Application.Queries
  fullName: Raftel.Application.Queries
  type: Namespace
  assemblies:
  - Raftel.Application
references:
- uid: Raftel.Application.Queries.IQuery`1
  commentId: T:Raftel.Application.Queries.IQuery`1
  href: Raftel.Application.Queries.IQuery-1.html
  name: IQuery<TResult>
  nameWithType: IQuery<TResult>
  fullName: Raftel.Application.Queries.IQuery<TResult>
  nameWithType.vb: IQuery(Of TResult)
  fullName.vb: Raftel.Application.Queries.IQuery(Of TResult)
  name.vb: IQuery(Of TResult)
  spec.csharp:
  - uid: Raftel.Application.Queries.IQuery`1
    name: IQuery
    href: Raftel.Application.Queries.IQuery-1.html
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Queries.IQuery`1
    name: IQuery
    href: Raftel.Application.Queries.IQuery-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: Raftel.Application.Queries.IQueryDispatcher
  commentId: T:Raftel.Application.Queries.IQueryDispatcher
  parent: Raftel.Application.Queries
  href: Raftel.Application.Queries.IQueryDispatcher.html
  name: IQueryDispatcher
  nameWithType: IQueryDispatcher
  fullName: Raftel.Application.Queries.IQueryDispatcher
- uid: Raftel.Application.Queries.IQueryHandler`2
  commentId: T:Raftel.Application.Queries.IQueryHandler`2
  href: Raftel.Application.Queries.IQueryHandler-2.html
  name: IQueryHandler<TQuery, TResult>
  nameWithType: IQueryHandler<TQuery, TResult>
  fullName: Raftel.Application.Queries.IQueryHandler<TQuery, TResult>
  nameWithType.vb: IQueryHandler(Of TQuery, TResult)
  fullName.vb: Raftel.Application.Queries.IQueryHandler(Of TQuery, TResult)
  name.vb: IQueryHandler(Of TQuery, TResult)
  spec.csharp:
  - uid: Raftel.Application.Queries.IQueryHandler`2
    name: IQueryHandler
    href: Raftel.Application.Queries.IQueryHandler-2.html
  - name: <
  - name: TQuery
  - name: ','
  - name: " "
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Queries.IQueryHandler`2
    name: IQueryHandler
    href: Raftel.Application.Queries.IQueryHandler-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TQuery
  - name: ','
  - name: " "
  - name: TResult
  - name: )
- uid: Raftel.Application.Queries.QueryDispatcher
  commentId: T:Raftel.Application.Queries.QueryDispatcher
  href: Raftel.Application.Queries.QueryDispatcher.html
  name: QueryDispatcher
  nameWithType: QueryDispatcher
  fullName: Raftel.Application.Queries.QueryDispatcher
- uid: Raftel.Application.Queries
  commentId: N:Raftel.Application.Queries
  href: Raftel.html
  name: Raftel.Application.Queries
  nameWithType: Raftel.Application.Queries
  fullName: Raftel.Application.Queries
  spec.csharp:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Queries
    name: Queries
    href: Raftel.Application.Queries.html
  spec.vb:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Queries
    name: Queries
    href: Raftel.Application.Queries.html
