### YamlMime:ManagedReference
items:
- uid: Raftel.Application.Queries.IQuery`1
  commentId: T:Raftel.Application.Queries.IQuery`1
  id: IQuery`1
  parent: Raftel.Application.Queries
  children: []
  langs:
  - csharp
  - vb
  name: IQuery<TResult>
  nameWithType: IQuery<TResult>
  fullName: Raftel.Application.Queries.IQuery<TResult>
  type: Interface
  source:
    remote:
      path: src/Raftel.Application/Queries/IQuery.cs
      branch: documentation
      repo: https://github.com/franciscofsl/Raftel
    id: IQuery
    path: src/Raftel.Application/Queries/IQuery.cs
    startLine: 9
  assemblies:
  - Raftel.Application
  namespace: Raftel.Application.Queries
  summary: Represents a query that returns a result of type <code class="typeparamref">TResult</code>.
  example: []
  syntax:
    content: 'public interface IQuery<TResult> : IRequest<Result<TResult>>'
    typeParameters:
    - id: TResult
      description: The type of the result produced by the query.
    content.vb: Public Interface IQuery(Of TResult) Inherits IRequest(Of Result(Of TResult))
  nameWithType.vb: IQuery(Of TResult)
  fullName.vb: Raftel.Application.Queries.IQuery(Of TResult)
  name.vb: IQuery(Of TResult)
references:
- uid: Raftel.Application.Queries
  commentId: N:Raftel.Application.Queries
  href: Raftel.html
  name: Raftel.Application.Queries
  nameWithType: Raftel.Application.Queries
  fullName: Raftel.Application.Queries
  spec.csharp:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Queries
    name: Queries
    href: Raftel.Application.Queries.html
  spec.vb:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Queries
    name: Queries
    href: Raftel.Application.Queries.html
