### YamlMime:ManagedReference
items:
- uid: Raftel.Application.Commands.ICommandHandler`1
  commentId: T:Raftel.Application.Commands.ICommandHandler`1
  id: ICommandHandler`1
  parent: Raftel.Application.Commands
  children: []
  langs:
  - csharp
  - vb
  name: ICommandHandler<TCommand>
  nameWithType: ICommandHandler<TCommand>
  fullName: Raftel.Application.Commands.ICommandHandler<TCommand>
  type: Interface
  source:
    remote:
      path: src/Raftel.Application/Commands/ICommandHandler.cs
      branch: feature/base-types
      repo: https://github.com/franciscofsl/Raftel
    id: ICommandHandler
    path: src/Raftel.Application/Commands/ICommandHandler.cs
    startLine: 9
  assemblies:
  - Raftel.Application
  namespace: Raftel.Application.Commands
  summary: Defines a handler for processing a command of type <code class="typeparamref">TCommand</code>.
  example: []
  syntax:
    content: 'public interface ICommandHandler<TCommand> : IRequestHandler<TCommand, Result> where TCommand : ICommand'
    typeParameters:
    - id: TCommand
      description: The type of command to handle.
    content.vb: Public Interface ICommandHandler(Of TCommand As ICommand) Inherits IRequestHandler(Of TCommand, Result)
  inheritedMembers:
  - Raftel.Application.Abstractions.IRequestHandler{{TCommand},Raftel.Domain.Abstractions.Result}.HandleAsync({TCommand})
  nameWithType.vb: ICommandHandler(Of TCommand)
  fullName.vb: Raftel.Application.Commands.ICommandHandler(Of TCommand)
  name.vb: ICommandHandler(Of TCommand)
references:
- uid: Raftel.Application.Commands
  commentId: N:Raftel.Application.Commands
  href: Raftel.html
  name: Raftel.Application.Commands
  nameWithType: Raftel.Application.Commands
  fullName: Raftel.Application.Commands
  spec.csharp:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Commands
    name: Commands
    href: Raftel.Application.Commands.html
  spec.vb:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Commands
    name: Commands
    href: Raftel.Application.Commands.html
- uid: Raftel.Application.Abstractions.IRequestHandler{{TCommand},Raftel.Domain.Abstractions.Result}.HandleAsync({TCommand})
  commentId: M:Raftel.Application.Abstractions.IRequestHandler{`0,Raftel.Domain.Abstractions.Result}.HandleAsync(`0)
  parent: Raftel.Application.Abstractions.IRequestHandler{{TCommand},Raftel.Domain.Abstractions.Result}
  definition: Raftel.Application.Abstractions.IRequestHandler`2.HandleAsync(`0)
  href: Raftel.Application.Abstractions.IRequestHandler-2.html#Raftel_Application_Abstractions_IRequestHandler_2_HandleAsync__0_
  name: HandleAsync(TCommand)
  nameWithType: IRequestHandler<TCommand, Result>.HandleAsync(TCommand)
  fullName: Raftel.Application.Abstractions.IRequestHandler<TCommand, Raftel.Domain.Abstractions.Result>.HandleAsync(TCommand)
  nameWithType.vb: IRequestHandler(Of TCommand, Result).HandleAsync(TCommand)
  fullName.vb: Raftel.Application.Abstractions.IRequestHandler(Of TCommand, Raftel.Domain.Abstractions.Result).HandleAsync(TCommand)
  spec.csharp:
  - uid: Raftel.Application.Abstractions.IRequestHandler{`0,Raftel.Domain.Abstractions.Result}.HandleAsync(`0)
    name: HandleAsync
    href: Raftel.Application.Abstractions.IRequestHandler-2.html#Raftel_Application_Abstractions_IRequestHandler_2_HandleAsync__0_
  - name: (
  - name: TCommand
  - name: )
  spec.vb:
  - uid: Raftel.Application.Abstractions.IRequestHandler{`0,Raftel.Domain.Abstractions.Result}.HandleAsync(`0)
    name: HandleAsync
    href: Raftel.Application.Abstractions.IRequestHandler-2.html#Raftel_Application_Abstractions_IRequestHandler_2_HandleAsync__0_
  - name: (
  - name: TCommand
  - name: )
- uid: Raftel.Application.Abstractions.IRequestHandler`2.HandleAsync(`0)
  commentId: M:Raftel.Application.Abstractions.IRequestHandler`2.HandleAsync(`0)
  href: Raftel.Application.Abstractions.IRequestHandler-2.html#Raftel_Application_Abstractions_IRequestHandler_2_HandleAsync__0_
  name: HandleAsync(TRequest)
  nameWithType: IRequestHandler<TRequest, TResponse>.HandleAsync(TRequest)
  fullName: Raftel.Application.Abstractions.IRequestHandler<TRequest, TResponse>.HandleAsync(TRequest)
  nameWithType.vb: IRequestHandler(Of TRequest, TResponse).HandleAsync(TRequest)
  fullName.vb: Raftel.Application.Abstractions.IRequestHandler(Of TRequest, TResponse).HandleAsync(TRequest)
  spec.csharp:
  - uid: Raftel.Application.Abstractions.IRequestHandler`2.HandleAsync(`0)
    name: HandleAsync
    href: Raftel.Application.Abstractions.IRequestHandler-2.html#Raftel_Application_Abstractions_IRequestHandler_2_HandleAsync__0_
  - name: (
  - name: TRequest
  - name: )
  spec.vb:
  - uid: Raftel.Application.Abstractions.IRequestHandler`2.HandleAsync(`0)
    name: HandleAsync
    href: Raftel.Application.Abstractions.IRequestHandler-2.html#Raftel_Application_Abstractions_IRequestHandler_2_HandleAsync__0_
  - name: (
  - name: TRequest
  - name: )
- uid: Raftel.Application.Abstractions.IRequestHandler{{TCommand},Raftel.Domain.Abstractions.Result}
  commentId: T:Raftel.Application.Abstractions.IRequestHandler{`0,Raftel.Domain.Abstractions.Result}
  parent: Raftel.Application.Abstractions
  definition: Raftel.Application.Abstractions.IRequestHandler`2
  href: Raftel.Application.Abstractions.IRequestHandler-2.html
  name: IRequestHandler<TCommand, Result>
  nameWithType: IRequestHandler<TCommand, Result>
  fullName: Raftel.Application.Abstractions.IRequestHandler<TCommand, Raftel.Domain.Abstractions.Result>
  nameWithType.vb: IRequestHandler(Of TCommand, Result)
  fullName.vb: Raftel.Application.Abstractions.IRequestHandler(Of TCommand, Raftel.Domain.Abstractions.Result)
  name.vb: IRequestHandler(Of TCommand, Result)
  spec.csharp:
  - uid: Raftel.Application.Abstractions.IRequestHandler`2
    name: IRequestHandler
    href: Raftel.Application.Abstractions.IRequestHandler-2.html
  - name: <
  - name: TCommand
  - name: ','
  - name: " "
  - uid: Raftel.Domain.Abstractions.Result
    name: Result
    href: Raftel.Domain.Abstractions.Result.html
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Abstractions.IRequestHandler`2
    name: IRequestHandler
    href: Raftel.Application.Abstractions.IRequestHandler-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TCommand
  - name: ','
  - name: " "
  - uid: Raftel.Domain.Abstractions.Result
    name: Result
    href: Raftel.Domain.Abstractions.Result.html
  - name: )
- uid: Raftel.Application.Abstractions.IRequestHandler`2
  commentId: T:Raftel.Application.Abstractions.IRequestHandler`2
  href: Raftel.Application.Abstractions.IRequestHandler-2.html
  name: IRequestHandler<TRequest, TResponse>
  nameWithType: IRequestHandler<TRequest, TResponse>
  fullName: Raftel.Application.Abstractions.IRequestHandler<TRequest, TResponse>
  nameWithType.vb: IRequestHandler(Of TRequest, TResponse)
  fullName.vb: Raftel.Application.Abstractions.IRequestHandler(Of TRequest, TResponse)
  name.vb: IRequestHandler(Of TRequest, TResponse)
  spec.csharp:
  - uid: Raftel.Application.Abstractions.IRequestHandler`2
    name: IRequestHandler
    href: Raftel.Application.Abstractions.IRequestHandler-2.html
  - name: <
  - name: TRequest
  - name: ','
  - name: " "
  - name: TResponse
  - name: '>'
  spec.vb:
  - uid: Raftel.Application.Abstractions.IRequestHandler`2
    name: IRequestHandler
    href: Raftel.Application.Abstractions.IRequestHandler-2.html
  - name: (
  - name: Of
  - name: " "
  - name: TRequest
  - name: ','
  - name: " "
  - name: TResponse
  - name: )
- uid: Raftel.Application.Abstractions
  commentId: N:Raftel.Application.Abstractions
  href: Raftel.html
  name: Raftel.Application.Abstractions
  nameWithType: Raftel.Application.Abstractions
  fullName: Raftel.Application.Abstractions
  spec.csharp:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Abstractions
    name: Abstractions
    href: Raftel.Application.Abstractions.html
  spec.vb:
  - uid: Raftel
    name: Raftel
    href: Raftel.html
  - name: .
  - uid: Raftel.Application
    name: Application
    href: Raftel.Application.html
  - name: .
  - uid: Raftel.Application.Abstractions
    name: Abstractions
    href: Raftel.Application.Abstractions.html
